[phases.setup]
nixPkgs = ["ffmpeg", "python311"]

[phases.install]
cmds = ["python3.11 -m venv /opt/venv", ". /opt/venv/bin/activate", "pip install -r requirements.txt"]

[start]
cmd = "python3.11 main.py"